services:
  transfer-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: transferapi:latest
    container_name: transfer-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - BasePath=/backend
      - Transferapi.ConnectionString=Host=postgres;Port=5432;Database=liventa_transfer;Username=liventa_user;Password=Liventa2025!
    networks:
      - liventa-network

networks:
  liventa-network:
    external: true
