services:
  transfer-api:
    build: .
    container_name: transfer-api
    restart: unless-stopped
    ports:
      - "5003:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Transferapi.ConnectionString=Host=host.docker.internal;Port=5432;Database=liventa_transfer;Username=liventa_user;Password=Liventa2025!
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: transfer-net
    external: false
